project:
  type: website

website:
  title: "blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  repo-url: https://github.com/hwz531/blog
  repo-actions: [source]

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



